env:
  browser: true
  commonjs: true
  es2021: true
  jquery: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules:
  no-console: 0
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - "./gulp**"
        - "./gulp/**/*.js"
